version: '3'
services:
  db:
    image: postgres:13.5
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  test-db:
    image: postgres:13.5
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - 5433:5432
    volumes:
      - test_db_data:/var/lib/postgresql/data

  web:
    build: .
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ./public:/app/public
      - ./tmp:/app/tmp
      - ./log:/app/log
    depends_on:
      - db
      - test-db
    stdin_open: true
    tty: true

volumes:
  db_data:
  test_db_data:
